datasources:
  default:
    url: jdbc:tc:mariadb:10:///db
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver

tracing:
  jaeger:
    enabled: false
consul:
  client:
    registration:
      enabled: false


jpa:
  default:
    entity-scan:
      packages:
        - "br.com.bota.entity"
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true