version: "3.9"  # optional since v1.27.0

##Apenas para build.
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123r
      MONGO_INITDB_DATABASE: entregadb
      
  produtodb:
    image: mariadb:10.5.8
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_USER: usr_product
      MYSQL_PASSWORD: 123r
      MYSQL_ROOT_PASSWORD: 123r
      MYSQL_DATABASE: produtodb

  clientedb:
    image: mariadb:10.5.8
    restart: always
    ports:
    - 3307:3306
    environment:
      MYSQL_USER: usr_client
      MYSQL_PASSWORD: 123r
      MYSQL_ROOT_PASSWORD: 123r
      MYSQL_DATABASE: clientedb

  pedidodb:
    image: mariadb:10.5.8
    container_name: pedido_db
    restart: always
    ports:
    - 3308:3306
    environment:
      MYSQL_USER: usr_pedido
      MYSQL_PASSWORD: 123r
      MYSQL_ROOT_PASSWORD: 123r
      MYSQL_DATABASE: pedidodb

  rabbitmq:
    image: rabbitmq:3-management
    hostname: localhost
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ${PWD}/docker/rabbit-conf/definitions-2-25.json:/opt/definitions.json:ro
      - ${PWD}/docker/rabbit-conf/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
    
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks: 
      - broker-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      
  kafka:
    image: confluentinc/cp-kafka:latest
    networks: 
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks: 
  broker-kafka:
    driver: bridge 
