micronaut:
  server:
    port: 8082
  application:
    name: clientes

  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    enabled: true

endpoints:
  prometheus:
    sensitive: false

datasources:
  default:
    url: jdbc:mariadb://localhost:3307/clientedb
    driverClassName: org.mariadb.jdbc.Driver
    username: usr_client
    password: 123r
    dialect: MYSQL

jpa:
  default:
    properties:
      hibernate:
        generate_statistics: true
        hbm2ddl:
          auto: update


tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1



consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"


hystrix.stream.enabled: false
