micronaut:
  server:
    port: 8084
  application:
    name: produtos
datasources:
  default:
    url: jdbc:mariadb://localhost:3306/productdb
    driverClassName: org.mariadb.jdbc.Driver
    username: usr_product
    password: 123r
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  custom:
    queue:
      name: "baixa_estoque"